# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: BrilliantGuo
subtitle:
  At the bottom of the well, it is destined to see only the sky at the wellhead.
  However, the starting point only affects the process of reaching your peak and does not determine the height you reach.
author: BrilliantGuo
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://brilliantguo.github.io # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Site settings
SEOTitle: brilliantguo-blog
# email: none
description: "brilliantGuo's blog"
keyword: "brilliantguo, blog"
header-img: img/header_img/home-bg-1-dark.jpg
signature: false #show signature
signature-img: 

# Build settings
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: "UA-XXXXXXXX-X" # Format: UA-xxxxxx-xx
ga_domain: yoursite

#Custom Setting Start

# Nav Settings
nav:
  Home: /
  Archives: /archive
  Categories: /categories
  About: /about

# SNS settings
github_username: brilliantGuo
twitter_username:
facebook_username:
zhihu_username:

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Welcome to visit, I'm BrilliantGuo!"
sidebar-avatar: img/avatar.jpg # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
  - search
  - featured-tags
  - short-about
  - visitor
  - recent-posts
  # - friends-blog
  - archive
  - category

## Search
search:
  enable: true
  path: search.xml
  field: post
  content: true

# widget behavior
## Archive
archive_type: "monthly"
show_count: true

## Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

## Friends
### { title: "Other", href: "#" },
friends:
  []

math:
  enable: true
  engine: mathjax

## music
music: false

# Custom Setting End

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
photography_dir: photography
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: zelda

#sitemap
sitemap:
  path: sitemap.xml
## Baidusitemap
baidusitemap:
path: baidusitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github:
    coding:
  branch: master

## share
share: true

# Comment
## This comment system is gitment
## gitment url: https://github.com/imsun/gitment
## gitalk url: https://github.com/gitalk/gitalk
comment:
  gitalk:
    enable: true
    client_id: 0a9e73417984941be377
    client_secret: 5d6aef968e54c87a88e13c53a31da5359079e466
    repo: git@github.com:brilliantGuo/brilliantguo.github.io.git
    owner: brilliantGuo
    distraction_free_mode: false
  gitment:
    enable: false
    owner: brilliantGuo
    repo:
    client_id:
    client_secret:
  livere:
    enable: false
  disqus:
    enable: false
    username:

# Tip
tip:
  enable: true
  copyright: This is copyright.
  content: false

# Background effects
## If there is no effect after modification, please empty the cache and try again.
## ⚠️ The following special effects will take up a lot of cpu resorces, please open it carefully.
bg_effects:
  enable: true
  line:
    enable: false
    color: 129,200,61
    pointColor: 129,200,61
    opacity: 0.7
    zIndex: -9
    count: 99
  mouse_click:
    enable: false
    content: '"🌱","🍀"'
    color: '"rgb(121,93,179)"
      ,"rgb(76,180,231)"
      ,"rgb(184,90,154)"'
  wave:
    enable: true

# Color Theme
## light , dark or star
## If you set the value of the `color_theme` to `dark`, set the value of the `highlight_theme` to `night` in `/theme/snail/config.yml`
## `mouse_control` is only valid for star themes
color_theme: light
mouse_control: false

# Visitor statistics
visitor:
  enable: true
  type:
